#define MEGABIT 1000000

#define RAM_CAPACITY_ROWS 1024
#define RAM_CAPACITY_COLUMNS 1024

#define FOUND_FAULT 5
#define NO_EXISTING_FAULT 6

// ### faults types
#define BROKEN_CELL 109
#define NO_FAULT 0
#define PNPSFK5 10
#define ANPSFK9 20

// ### values
#define PNPSFK5_VALUE 0

/*
TOP_LEFT TOP_MIDDLE TOP_RIGHT

LEFT_MIDDLE ###BASE RIGHT_MIDDLE

BOTTOM_LEFT BOTTOM_MIDDLE BOTTOM_RIGHT
*/

//links
#define TOP_MIDDLE 12

#define BOTTOM_MIDDLE 22

#define LEFT_MIDDLE 32
#define RIGHT_MIDDLE 42

// apn
#define APN_TOP_RIGHT 50
#define APN_TOP_LEFT 51
#define APN_TOP_MIDDLE 52

#define APN_BOTTOM_RIGHT 53
#define APN_BOTTOM_LEFT 54
#define APN_BOTTOM_MIDDLE 55

#define APN_LEFT_MIDDLE 56
#define APN_RIGHT_MIDDLE 57
